name: nginx-extras

on:
  push:
    branches:
      - main
    paths:
      - nginx-extras/*
      - .github/workflows/nginx-extras.yml
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"

env:
  BUILD_VERSION: "git"
  OPENSSL_VERSION: "3.0.0"
  PCRE_VERSION: "8.45"
  DOCKER_CLI_EXPERIMENTAL: enabled
  REPOSITORY: ${{ github.actor }}/${{ github.workflow }}

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
      - name: Source checkout
        uses: actions/checkout@v2

      - name: Setup QEMU
        id: qemu
        uses: docker/setup-qemu-action@v2

      - name: Setup Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Set Docker metadata
        id: docker_meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REPOSITORY }}
          labels: |
            org.opencontainers.image.version=${{ env.BUILD_VERSION }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.title=${{ env.REPOSITORY }}

      - name: GitHub login
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: DockerHub login
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: ${{ github.event_name != 'pull_request' }}
          context: ${{ github.workflow }}
          file: ${{ github.workflow }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          build-args: BUILD_VERSION
          cache-from: type=gha, scope=${{ github.workflow }}-ubuntu
          cache-to: type=gha, scope=${{ github.workflow }}-ubuntu, mode=max
          labels: ${{ steps.docker_meta.outputs.labels }}
          tags: |
            docker.io/${{ env.REPOSITORY }}:${{ env.BUILD_VERSION }}-ubuntu
            ghcr.io/${{ env.REPOSITORY }}:${{ env.BUILD_VERSION }}-ubuntu
